safe: true
permalink: pretty
markdown: kramdown

title: Öppna Mångfaldsdata
author: Open Knowledge Sverige
description: Användardriven lista om företag som har gett ut data om deras anställdas mångfald, inklusive vilket år och om det gjorts med DCAT-AP, den öppna standarden för länkade öppna data.
url: http://oppnamangfaldsdata.se
repo: https://github.com/okfse/oppnamangfaldsdata
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
