safe: true
permalink: pretty
markdown: kramdown

title: Öppen Mångfaldsdata
author: Open Knowledge Sweden
description:
    Förteckning av företag som har gett ut data om deras anställdas mångfald, inklusive EEO-1 formulär och .
url: http://opendiversitydata.org
repo: https://github.com/okfse/opendiversitydata
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
